import type { Project } from "./types";

// Every claim below was read from the repo's README/docs or stated by the owner.
// TODO(owner): confirm permission to name Express Rafting publicly.
export const projects: Project[] = [
  {
    slug: "express-ops",
    name: "Express Ops",
    tagline: "Operations platform that turns manifest photos into driver lists, double-booking checks and customer documents.",
    order: 1,
    featured: true,
    role: "Sole developer, end to end",
    status: "In daily use by the operations team",
    summary:
      "Tour-transfer teams were rebuilding daily driver lists and customer documents by hand from photographed manifests. I built a role-based web app that reads the manifests, reconciles them against the totals printed on the page, and produces the finished documents.",
    highlights: [
      "Manifest extractor: OCR per image, reconciled against the footer totals; failures and mismatches go to an editable review queue with undo.",
      "Driver's List: batches of per-shift screenshots become one styled XLSX with per-driver subtotals and a grand total.",
      "List Maker: imports group workbooks, classifies bookings, routes languages by agency and phone country, exports formatted DOCX lists.",
      "Double-booking detector ranks duplicate guests across or within agencies by severity.",
      "Customer Lists with role-aware import, live restaurant rosters, presence and audit workflows. Guides see only their own surface.",
      "Saves the operations team roughly 3–5 hours a day.",
    ],
    stack: ["Next.js", "TypeScript", "Convex", "Mistral OCR", "Docker Compose", "GitHub Actions", "Vitest"],
    security: [
      "Every push and PR runs a dependency audit, lint, unit tests, typecheck and a production build.",
      "A green push to main deploys the same commit to the production host over SSH, then verifies the sign-in endpoint.",
      "Recent audit failures (ip-address, undici advisories) were patched via lockfile-only updates.",
      "Server-to-server calls use internal Docker-network URLs so they never hit the Cloudflare managed challenge.",
      "Role-gated navigation, MFA in account settings, and a non-root multi-stage Docker image.",
    ],
    preview: "web",
    links: [],
  },
  {
    slug: "viya",
    name: "Viya",
    tagline: "Multi-tenant B2B SaaS that turns raw manifests into reviewed passenger data, optimized routes and driver dispatch.",
    order: 2,
    featured: true,
    role: "Builder and sole developer",
    status: "Early MVP, built as a product for tour agencies beyond a single customer",
    summary:
      "Viya generalizes the Express Ops domain into a SaaS for any tour agency: ingest Excel or PDF manifests, extract structured data with a routable set of LLM and OCR providers, plan routes and dispatch drivers over the messaging apps they already use.",
    highlights: [
      "Four parse providers (Docling, native sheet, Mistral OCR, LlamaParse) and five LLM extraction providers behind one routing layer.",
      "Route generation with manual reordering on a dual map stack: Google Maps and MapLibre with OSRM directions.",
      "Driver dispatch over WhatsApp, Telegram and Slack, including inbound status replies and interactive confirmations.",
      "Fleet and capacity management; weather widget backed by MET Norway data with caching.",
      "Python FastAPI microservice for document parsing.",
    ],
    stack: ["Next.js", "TypeScript", "Convex", "Clerk", "Python / FastAPI", "Docling", "MapLibre", "Sentry", "Docker"],
    security: [
      "Clerk authentication with tenant-scoped access controls in the Convex backend.",
      "Sentry across browser, server and edge runtimes, plus the Python service, with documented privacy rules.",
      "Separate local, staging and production stacks; local backend and dashboard bind to loopback only.",
      "Security best-practice, performance and UI/UX audit reports kept in the repo.",
      "Linting and static analysis configured for both TypeScript and Python (ESLint, flake8, mypy, DeepSource).",
    ],
    preview: "web",
    links: [],
  },
  {
    slug: "gravel",
    name: "Gravel",
    tagline: "Guardrails for AI agents: scope validation, human approvals, emergency stop and an audit trail.",
    order: 3,
    featured: true,
    role: "Author",
    status: "Rust workspace with a terminal UI",
    summary:
      "AI agents that can run tools need a human in the loop. Gravel is a terminal app that mediates every tool call: it checks scope, asks the operator to approve, can halt everything instantly, and records what happened.",
    highlights: [
      "Shared domain layer for sessions, tool requests and configuration.",
      "Security crate for scope validation, approvals, emergency stop and audit.",
      "MCP client and interceptor layer for tool execution.",
      "Agent runtime with pluggable model backends, plus a terminal UI with session resume.",
    ],
    stack: ["Rust", "MCP", "Terminal UI", "Cargo workspace"],
    security: [
      "Defensive by design: every tool request passes scope validation and operator approval before it runs.",
      "Emergency stop and an audit trail of what ran.",
      "Cargo workspace with format, clippy and test commands as the quality gate.",
    ],
    preview: "terminal",
    links: [],
  },
  {
    slug: "getit",
    name: "getit",
    tagline: "File-host downloader with a terminal UI, a scripting CLI and an MCP server so AI agents can drive it.",
    order: 4,
    featured: false,
    role: "Author",
    status: "Packaged for PyPI and Homebrew; used personally",
    summary:
      "One command downloads from GoFile, PixelDrain, MediaFire, 1Fichier, UploadFlix, Mega.nz and Anonfile.de, with a dashboard-style TUI for queue management.",
    highlights: [
      "Concurrent downloads with smart resume, speed limits and recursive folder support.",
      "Client-side Mega.nz AES-CTR decryption; MD5/SHA256 integrity checks.",
      "Built-in MCP server: agents can list remote folders, start, poll and cancel downloads.",
      "Async engine, SQLite-backed task registry and an event bus for progress streaming.",
    ],
    stack: ["Python", "asyncio", "Textual", "SQLite", "MCP"],
    security: [
      "Credentials and tokens are read from environment variables rather than config files.",
      "Integrity verification of downloaded files; password-protected link handling.",
      "CI plus automated PR review configured on the repository.",
    ],
    preview: "terminal",
    links: [],
  },
  {
    slug: "amc-prep",
    name: "AMC Prep",
    tagline: "Gamified, AI-coached exam preparation for medical graduates.",
    order: 5,
    featured: false,
    role: "Builder",
    status: "Product spec and web app",
    summary:
      "A question bank framed as virtual hospital rotations: topic, challenge and exam-simulation modes, layered explanations, streaks and quests, and a weakness model that decides what to practise next.",
    highlights: [
      "Weakness analysis combining accuracy, confidence and recency to drive challenge sessions.",
      "Clinical Poker pattern-recognition mini-game.",
      "Admin tooling for question quality, broadcasts and campaigns, specified with role-based access.",
    ],
    stack: ["Next.js", "Convex", "Clerk", "TypeScript"],
    security: [],
    preview: "web",
    links: [],
  },
  {
    slug: "review-router",
    name: "Review Router",
    tagline: "One-tap landing page that sends customers from a QR code to the review site where their booking lives.",
    order: 6,
    featured: false,
    role: "Developer",
    status: "Built for one-click Vercel deployment",
    summary:
      "Customers scan a QR code at the end of a tour and reach Google, GetYourGuide, Viator or Booking.com in one tap, with channel-click analytics to prove the friction is low.",
    highlights: [
      "Mobile-first Next.js page; channels configured in one file.",
      "Per-channel click events for conversion visibility.",
    ],
    stack: ["Next.js", "Tailwind CSS", "Vercel Analytics"],
    security: [],
    preview: "web",
    links: [],
  },
  {
    slug: "callaudioguard",
    name: "CallAudioGuard",
    tagline: "macOS menu-bar utility that detects active calls and keeps audio on the right device.",
    order: 7,
    featured: false,
    role: "Author",
    status: "Native Swift app with Homebrew cask packaging",
    summary:
      "A small native app that watches for active calls and manages audio devices so a call never lands on the wrong output.",
    highlights: ["Active call detection and audio device management.", "Menu-bar UI; Makefile and Homebrew cask for distribution."],
    stack: ["Swift", "macOS", "Xcode"],
    security: [],
    preview: "menubar",
    links: [],
  },
];

export const getProject = (slug: string) => projects.find((p) => p.slug === slug);
